### ISSUE TITLE
how to visualize arcs in higlass

### ISSUE THREAD

**Issue by vivekbhr** [higlass/higlass-arcs#1]
Hi there

I have higlass-docker running and managed via [higlass-manage](https://github.com/higlass/higlass-manage). I have also prepared my arcs file in the "bedpe" format (with the score as the 7th column). but I don't see how to make it visible after ingest. There's no documentation about arcs in [higlass-docs](https://docs.higlass.io/track_types.html). Does this module need to be installed separately? How shall I proceed?

Best,
Vivek

**Comment by pkerpedjiev** [comment]
Hey Vivek,

The arcs track is still a bit experimental so it's not easy to add. But it is possible.

If you use the latest docker container and you ingest your data with `--filetype beddb --datatype bedlike`. Add your data as a `bedlike` track from the Add Track Dialog. Once it's loaded, open the the viewconf editor:

![image](https://user-images.githubusercontent.com/2143629/81838196-a8073180-94fa-11ea-8e16-95731994dc9f.png)

Scroll down to the section for your track (look for `type:bedlike`). Change that to `type: 1d-arcs` and delete the `uid:...` section for that track. Save the viewconf and you should be able to see the arcs track.

We'll improve that process and make it easier to add as a track shortly.

**Comment by vivekbhr** [comment]
thanks @pkerpedjiev . Do I need to run `clodius aggregate` first?

**Comment by pkerpedjiev** [comment]
Yes, you need to run `clodius aggregate bedfile` on the bedfile and  then ingest it using `--filetype beddb --datatype bedlike`.

**Comment by vivekbhr** [comment]
I thought of importing it as bedpe file like:

```
clodius aggregate bedpe --assembly mm10  --chr1-col 1 --from1-col 2 --to1-col 3   --chr2-col 4 --from2-col 5 --to2-col 6 --output-file /tmp/test.arcs
```

followed by:

```
sudo higlass-manage ingest --filetype beddb --datatype bedlike /tmp/test.arcs
```

but I couldn't see anything.. I would try `bedfile` now

**Comment by vivekbhr** [comment]
I am still unable to see the arcs. I can see the individual positions though. 

Does this need any update? Here's what I have in `higlass-app/version.txt` 

```
SERVER_VERSION: 1.14.1
WEB_APP_VERSION: 1.1.8
LIBRARY_VERSION: 1.9.3
HIPILER_VERSION: 1.4.0
MULTIVEC_VERSION: 0.2.3
CLODIUS_VERSION: 0.14.3
TIME_INTERVAL_TRACK_VERSION: 0.2.0-rc.2
LINEAR_LABELS_TRACK: 0.1.6
LABELLED_POINTS_TRACK: 0.1.12
BEDLIKE_TRIANGLES_TRACK_VERSION: 0.1.2
RANGE_TRACK_VERSION: 0.1.1
PILEUP_VERSION: 0.2.11
```
![export](https://user-images.githubusercontent.com/8420267/82078097-df373780-96e0-11ea-993e-e4398e11ebc0.png)

**Comment by pkerpedjiev** [comment]
I think they're there. Just zoom in to one of the bars on the top :-)

**Comment by vivekbhr** [comment]
@pkerpedjiev oh yes I see them now! I think I was expecting some over longer distances. My bad! 

Are, there any limitations in visualizing one-to-many kind of connections?

**Comment by pkerpedjiev** [comment]
Hmm, I haven't tried out one to many. It shouldn't be a problem if you have multiple bed lines:

```
chr1 1000 3000
chr1 1000 5000
```

**Comment by vivekbhr** [comment]
Ok, I'll play around with it. Thanks a lot for the fast replies! The tool is amazing
